### ISSUE TITLE
RTH location issue

### ISSUE THREAD

**Issue by prestondillon86** [dbaldwin/ScribbleDrone#16]
From Randy: "One glaring thing happened this evening.  It got confused and was not coming back to the launch point.  It was trying to land in the water some of the times.  So I had to watch it .... and override the landing process .... some of the time."

--perhaps upon completion we don't RTH and simply kick into hover / hold position until further commands given?

**Comment by dbaldwin** [comment]
Can we get Randy over here to comment? One thing we know about the SDK is that if the aircraft is < 20m from the takeoff location it will land right where it is instead of coming home. I bet that's what is happening here.

**Comment by rkostichka** [comment]
Can we have a toggle on the pre-launch page to disable or enable .... The RTH function.

**Comment by dbaldwin** [comment]
Good idea. What do you think the option should be? Here are what the SDK allows us to do:

1. RTH

2. Do nothing (drone just stays in position at the last waypoint)

3. Land in place (let's definitely not do this!)

4. Go back to the first waypoint

I propose we give the option to do 1 or 2. Thoughts?
